package com.android.tripbook.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)




//val md_theme_light_primary = Color(0xFF00677F)
//val md_theme_light_onPrimary = Color(0xFFFFFFFF)
//val md_theme_light_primaryContainer = Color(0xFFB4EBFF)
//val md_theme_light_onPrimaryContainer = Color(0xFF001F28)
//val md_theme_light_secondary = Color(0xFF4C626A)
//val md_theme_light_onSecondary = Color(0xFFFFFFFF)
//val md_theme_light_secondaryContainer = Color(0xFFCFE6F1)
//val md_theme_light_onSecondaryContainer = Color(0xFF071E25)
//val md_theme_light_tertiary = Color(0xFF5A5C7E)
//val md_theme_light_onTertiary = Color(0xFFFFFFFF)
//val md_theme_light_tertiaryContainer = Color(0xFFE0E0FF)
//val md_theme_light_onTertiaryContainer = Color(0xFF171937)
//val md_theme_light_error = Color(0xFFBA1A1A)
//val md_theme_light_onError = Color(0xFFFFFFFF)
//val md_theme_light_errorContainer = Color(0xFFFFDAD6)
//val md_theme_light_onErrorContainer = Color(0xFF410002)
//val md_theme_light_background = Color(0xFFFBFCFE)
//val md_theme_light_onBackground = Color(0xFF191C1D)
//val md_theme_light_surface = Color(0xFFFBFCFE)
//val md_theme_light_onSurface = Color(0xFF191C1D)
//val md_theme_light_surfaceVariant = Color(0xFFDBE4E7)
//val md_theme_light_onSurfaceVariant = Color(0xFF3F484B)
//val md_theme_light_outline = Color(0xFF6F797B)
//val md_theme_light_inverseOnSurface = Color(0xFFEEF1F2)
//val md_theme_light_inverseSurface = Color(0xFF2E3132)
//val md_theme_light_inversePrimary = Color(0xFF5BD4F3)
//val md_theme_light_surfaceDim = Color(0xFFDBDCDC)
//val md_theme_light_surfaceBright = Color(0xFFFBFCFE)
//val md_theme_light_surfaceContainerHighest = Color(0xFFE0E2E3)
//val md_theme_light_surfaceContainerHigh = Color(0xFFE5E7E8)
//val md_theme_light_surfaceContainer = Color(0xFFEBECEE)
//val md_theme_light_surfaceContainerLow = Color(0xFFF1F2F3)
//val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
//
//
//val md_theme_dark_primary = Color(0xFF5BD4F3)
//val md_theme_dark_onPrimary = Color(0xFF003543)
//val md_theme_dark_primaryContainer = Color(0xFF004D60)
//val md_theme_dark_onPrimaryContainer = Color(0xFFB4EBFF)
//val md_theme_dark_secondary = Color(0xFFB3CAD5)
//val md_theme_dark_onSecondary = Color(0xFF1E333C)
//val md_theme_dark_secondaryContainer = Color(0xFF354A52)
//val md_theme_dark_onSecondaryContainer = Color(0xFFCFE6F1)
//val md_theme_dark_tertiary = Color(0xFFC2C4FF)
//val md_theme_dark_onTertiary = Color(0xFF2D2E4D)
//val md_theme_dark_tertiaryContainer = Color(0xFF434565)
//val md_theme_dark_onTertiaryContainer = Color(0xFFE0E0FF)
//val md_theme_dark_error = Color(0xFFFFB4AB)
//val md_theme_dark_onError = Color(0xFF690005)
//val md_theme_dark_errorContainer = Color(0xFF93000A)
//val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
//val md_theme_dark_background = Color(0xFF191C1D)
//val md_theme_dark_onBackground = Color(0xFFE0E2E3)
//val md_theme_dark_surface = Color(0xFF191C1D)
//val md_theme_dark_onSurface = Color(0xFFE0E2E3)
//val md_theme_dark_surfaceVariant = Color(0xFF3F484B)
//val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CB)
//val md_theme_dark_outline = Color(0xFF899295)
//val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
//val md_theme_dark_inverseSurface = Color(0xFFE0E2E3)
//val md_theme_dark_inversePrimary = Color(0xFF00677F)
//val md_theme_dark_surfaceDim = Color(0xFF191C1D)
//val md_theme_dark_surfaceBright = Color(0xFF414749)
//val md_theme_dark_surfaceContainerHighest = Color(0xFF34393B)
//val md_theme_dark_surfaceContainerHigh = Color(0xFF292E30)
//val md_theme_dark_surfaceContainer = Color(0xFF1F2325)
//val md_theme_dark_surfaceContainerLow = Color(0xFF1C2022)
//val md_theme_dark_surfaceContainerLowest = Color(0xFF0F1416)