# --- VERSIONS SECTION ---
[versions]
accompanistPlaceholder = "0.35.0-alpha" # Keep if you use it and it's compatible
agp = "8.4.1"
coilCompose = "2.5.0"
# kotlin = "1.9.0" # Likely too old
kotlin = "1.9.22" # Or newer, check compatibility with your Compose BOM / AGP
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
kotlinxCoroutinesAndroid = "1.7.3"
kotlinxCoroutinesPlayServices = "1.6.4"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.8.0" # This itself uses Compose, ensure compatibility or let BOM handle a compatible version if available
composeBom = "2024.05.00" # This is your source of truth for Compose libs
coreSplashscreen = "1.0.1"

mapsCompose = "4.3.0"
mapsUtilsKtx = "5.0.0"
playServicesMaps = "19.2.0" # Check if this is the latest or if there's a BOM for Play Services
playServicesLocation = "21.3.0" # Check if this is the latest

# REMOVE these explicit Compose overrides:
# material3Version = "1.3.2"
# materialIconsExtendedVersion = "1.7.8"
# uiToolingPreviewAndroid = "1.7.8"
# foundationLayoutAndroid = "1.7.8"
# runtimeAndroid = "1.7.8"
# uiAndroid = "1.7.8"
# lifecycleRuntimeCompose = "2.9.0" # BOM will provide androidx.lifecycle:lifecycle-runtime-compose

[libraries]
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanistPlaceholder" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }

maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
maps-utils-ktx = { module = "com.google.maps.android:maps-utils-ktx", version.ref = "mapsUtilsKtx" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

# --- Compose Libraries (Versions managed by BOM) ---
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" } # For debug builds
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" } # REMOVED explicit old version
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.7.7" } # Often has its own lifecycle, check latest compatible
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose" } # Version from BOM

# Test libraries for Compose (Versions from BOM)
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Play Services
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }


# REMOVE these aliases that point to specific overridden versions:
# androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtendedVersion" } # Now uses BOM
# androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Version" } # Now uses BOM
# androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
# androidx-foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version.ref = "foundationLayoutAndroid" }
# androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
# androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }